services:

  # ---------------- FRONTEND ----------------
  frontend:
    container_name: frontend
    build:
      context: ./Front
      dockerfile: docker/Dockerfile
    env_file:
      - ./.env
    networks:
      - Ja_Ostadi_network
    ports:
      - "5173:80"

  # ---------------- DATABASE ----------------
  database:
    container_name: jaostadi_db
    image: mysql:latest
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - jaostadi_db:/var/lib/mysql
    networks:
      - Ja_Ostadi_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      start_period: 5s

  # ---------------- PHPMYADMIN ----------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - database
    networks:
      - Ja_Ostadi_network

  # ---------------- BACKEND ----------------
  backend:
    container_name: backend
    build:
      context: ./Back
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "5005:3003"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - Ja_Ostadi_network
    restart: unless-stopped

  # ---------------- MONITORING ----------------
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: my-secret-pw
    networks:
      - Ja_Ostadi_network

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - Ja_Ostadi_network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./Back/logs/app.log:/var/log/app/app.log
      - ./Back/docker/promtail-config.yaml:/etc/promtail/promtail.yaml
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - Ja_Ostadi_network

volumes:
  jaostadi_db:

networks:
  Ja_Ostadi_network:
    external: true
    name: Ja_Ostadi_network

