version: '1.0'

services:
  # app:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile
  #   container_name: go-app
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     DB_HOST: mysql
  #     DB_PORT: 3306
  #     DB_USER: root
  #     DB_PASS: ""
  #     DB_NAME: mydatabase
  #   depends_on:
  #     - mysql
  #   networks:
  #     - project_network

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
      MYSQL_DATABASE: ja-ostadi
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - project_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - project_network

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - project_network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ../logs/app.log:/var/log/app/app.log
      - ./promtail-config.yaml:/etc/promtail/promtail.yaml
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - project_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: my-secret-pw
    depends_on:
      - loki
    networks:
      - project_network


networks:
  project_network:

volumes:
  mysql_data:
